version: "3.9"
services:
  backend:
    container_name: compose-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: kupipodariday-backend
    restart: unless-stopped
    ports:
      - 4000:3000
    env_file:
      - backend/.env
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: compose-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kupipodariday-frontend
    ports:
      - 5000:80
    networks:
      - frontend

  postgres:
    container_name: compose-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - backend/.env
    networks:
      - backend

  adminer:
    container_name: compose-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:

